# Generated by Django 4.1.7 on 2023-06-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("miniapp", "0002_billingdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("account_holder_name", models.CharField(max_length=100)),
                ("bank_name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                (
                    "billing_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miniapp.billingdetails",
                    ),
                ),
            ],
        ),
    ]
