# Generated by Django 4.1.7 on 2023-06-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miniapp", "0003_bankdetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankDetails",
        ),
        migrations.DeleteModel(
            name="BillingDetails",
        ),
    ]
