# Generated by Django 4.2.2 on 2023-06-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
    ]
