# Generated by Django 4.1.7 on 2023-06-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_cart_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pin_code", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("account_holder_name", models.CharField(max_length=100)),
                ("bank_name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                (
                    "billing_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.billingdetails",
                    ),
                ),
            ],
        ),
    ]
